@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <h1>The Howling Man</h1>
    </div>
    <div class="row justify-content-center">
        <h4>"You can catch the Devil, but you can't hold him long"</h4>
    </div>
    <div class="row">
        <p>The story is told in a flashback by an American called David Ellington. While on a walking trip through post–World War I Europe (circa 1925), Ellington becomes lost, is drenched by rain, and seeks shelter in a nearby castle (Wolfring Castle) near the village of Schwartzhoff. He is told to leave immediately but hears a disturbing wolf-like howl coming from somewhere in the castle. Unable to get answers from anyone, he turns to leave but collapses, shivering. Upon waking inside the castle, Ellington hears the howl again and goes to investigate. In the bowels of the castle, he finds a bedraggled but cultured and intelligent man in a cell. The man claims to be a prisoner of an insane religious order, locked up because he kissed his sweetheart in public. Ellington is seen talking to the prisoner, and is taken to a meeting with the leader of the order, Brother Jerome, who explains that the prisoner is not a man, but rather the devil himself. He has been locked up in the room using the "Staff of Truth" to bar the door since shortly after World War I. He had come to the village to corrupt it, but Jerome had recognized him for what he was and imprisoned him. His actions have given the world five years of relative peace, and mankind has been creating its own evil during that time. Ellington becomes convinced that Jerome is insane. Fearing for his safety, he pretends to believe the incredible story. Jerome is not fooled, however, and assigns another brother to watch him. Ellington waits until his guard falls asleep and creeps down to the cell. Seeing that the staff which held the door shut was easily within reach of the imprisoned man, Ellington briefly wonders why he hasn't simply removed it himself. At the man's urging, he removes the staff and releases the prisoner. When the prisoner exits the cell, he pins Ellington to the floor with a wave of his hand from across the hall. As he walks toward the exit, he begins to change, taking on the appearance of the devil with each step before departing the castle in a plume of smoke. Jerome finds the collapsed Ellington and sadly explains that the inability to recognize the devil has always been Man's great weakness. The flashback ends, and we find Ellington explaining to a hotel maid that he has spent the time since then hunting for the devil to atone for his mistake, through World War II, the Korean War, and the development of nuclear weapons. He finally succeeded; he has him locked in a closet barred by a similarly shaped staff, and he intends to return him to the castle and Brother Jerome's keeping. He warns the skeptical housekeeper not to remove the staff under any circumstances while he goes to make his final preparations. As soon as Ellington leaves, the maid hears a disturbing howl from behind the door, and in her curiosity and disbelief of Ellington's story, removes the Staff of Truth.</p>
    </div>
</div>
@endsection